### ISSUE TITLE
Pair Programming - Unit Testing

### ISSUE THREAD

**Issue by cthoyt** [bio2bel/interpro#3]
- Make reusable unit tests
- set up Tox to run them
- set up build matrix on Travis

**Comment by aramgrigoryan** [comment]
done?

**Comment by cthoyt** [comment]
Not yet! We still need to set up the build matrix on travis-ci. It's actually not so hard though. I think we just have to add to `.travis.yml`
```
env:
    - TOXENV=py
    - TOXENV=deploy
```

To make it do testing and deployment. This is better for the case when there are multiple types of tests though. It would be better to do a build stage thing and have it run the tests (and make sure they pass) before doing the deployment. Lets call it closed for now.
