### ISSUE TITLE
Add InterPro to GO Annotations

### ISSUE THREAD

**Issue by cthoyt** [bio2bel/interpro#9]
The ultimate goal of this sub-project is to use the GO annotations for protein families to check if BEL statements in a graph containing a molecular activity could really have that molecular activity (lots of checking necessary for manually curated and text-mining results)

- [ ]  Read http://www.ebi.ac.uk/GOA/InterPro2GO
- [ ]  Add data model for GO entries
- [ ]  Add data model for interpro entry - go
- [ ]  Implement downloader for interpro2go data
- [ ]  Implement parser for interpro2go data
- [ ]  Implement loader for interpro2go data (use a subclass of main data manager)

Later we'll write unit tests for a graph checker

**Comment by aramgrigoryan** [comment]
there is a mapping file from interpro to go on ebi website, created by interpro team, isn't that better?

**Comment by cthoyt** [comment]
Is it not the same file? Either one is fine.

**Comment by aramgrigoryan** [comment]
it seems to be
